import os

import pytest

from ocr_local import cv2, PyTessBaseAPI, PSM, OEM, OcrCheck, TesserocrPool

image_base_path = 'ressources'
expected_results = {
    '101.png': [
        ('Neo', 'S3', 'Intacte', '4'),
        ('Neo', 'S5', 'Intacte', '26'),
        ('Neo', 'S12', 'Intacte', '1'),
        ('Neo', 'S13', 'Intacte', '1'),
        ('Neo', 'T2', 'Intacte', '10'),
        ('Neo', 'T3', 'Intacte', '7'),
        ('Neo', 'V1', 'Intacte', '6'),
        ('Neo', 'V2', 'Intacte', '3'),
        ('Neo', 'V3', 'Intacte', '4'),
        ('Neo', 'Z2', 'Intacte', '1'),
        ('Neo', 'Z3', 'Intacte', '2'),
        ('Neo', 'Z4', 'Intacte', '2'),
        ('Neo', 'Z5', 'Intacte', '8'),
        ('Requiem', 'II', 'Intacte', '3'),
        ('Requiem', 'III', 'Intacte', '3'),
        ('Requiem', 'IV', 'Intacte', '5')
    ],
    '100.png': [
        ('Axi', 'A1', 'Intacte', '3'),
        ('Axi', 'A10', 'Intacte', '4'),
        ('Axi', 'A11', 'Intacte', '1'),
        ('Axi', 'B2', 'Intacte', '1'),
        ('Axi', 'B3', 'Intacte', '6'),
        ('Axi', 'B4', 'Intacte', '7'),
        ('Axi', 'C5', 'Intacte', '7'),
        ('Axi', 'E1', 'Intacte', '12'),
        ('Axi', 'E2', 'Intacte', '1'),
        ('Axi', 'K1', 'Intacte', '1'),
        ('Axi', 'L5', 'Intacte', '1'),
        ('Axi', 'N1', 'Eclatante', '1'),
        ('Axi', 'N2', 'Intacte', '3'),
        ('Axi', 'N3', 'Intacte', '1'),
        ('Axi', 'N4', 'Intacte', '1'),
        ('Axi', 'N5', 'Intacte', '1'),
        ('Axi', 'P2', 'Intacte', '2'),
        ('Axi', 'S1', 'Intacte', '4'),
        ('Axi', 'S5', 'Intacte', '1'),
        ('Axi', 'S6', 'Intacte', '4')
    ],
    '1.png': [
        ('Meso', 'M2', 'Intacte', '3'),
        ('Meso', 'M3', 'Intacte', '8'),
        ('Meso', 'N1', 'Eclatante', '2'),
        ('Meso', 'N2', 'Intacte', '1'),
        ('Meso', 'N3', 'Intacte', '3'),
        ('Meso', 'N5', 'Intacte', '5'),
        ('Meso', 'O1', 'Intacte', '5'),
        ('Meso', 'O2', 'Intacte', '7'),
        ('Meso', 'O3', 'Intacte', '1'),
        ('Meso', 'P1', 'Intacte', '4'),
        ('Meso', 'R1', 'Intacte', '10'),
        ('Meso', 'S1', 'Intacte', '1'),
        ('Meso', 'S2', 'Eclatante', '5'),
        ('Meso', 'S3', 'Intacte', '3'),
        ('Meso', 'S5', 'Intacte', '1'),
        ('Meso', 'S7', 'Intacte', '3'),
        ('Meso', 'S8', 'Intacte', '1'),
        ('Meso', 'T1', 'Intacte', '3'),
        ('Meso', 'T2', 'Intacte', '4'),
        ('Meso', 'T3', 'Intacte', '12'),
    ],
    '2.png': [
        ('Neo', 'Z2', 'Intacte', '7'),
    ],
    '3.png': [
        ('Meso', 'V1', 'Intacte', '1'),
        ('Meso', 'V2', 'Intacte', '2'),
        ('Meso', 'V3', 'Intacte', '1'),
        ('Meso', 'Z1', 'Intacte', '5'),
        ('Meso', 'Z2', 'Intacte', '2'),
        ('Meso', 'Z3', 'Intacte', '9'),
        ('Neo', 'A2', 'Intacte', '5'),
        ('Neo', 'B2', 'Intacte', '10'),
        ('Neo', 'B3', 'Intacte', '1'),
        ('Neo', 'B4', 'Intacte', '5'),
        ('Neo', 'B5', 'Intacte', '3'),
        ('Neo', 'C1', 'Intacte', '2'),
        ('Neo', 'E1', 'Intacte', '1'),
        ('Neo', 'F1', 'Intacte', '1'),
        ('Neo', 'G1', 'Intacte', '7'),
        ('Neo', 'H1', 'Intacte', '1'),
        ('Neo', 'K1', 'Intacte', '11'),
        ('Neo', 'L1', 'Intacte', '8'),
        ('Neo', 'M1', 'Intacte', '7'),
        ('Neo', 'M2', 'Intacte', '5')
    ],
    '4.png': [
        ('Axi', 'A4', 'Intacte', '1'),
        ('Axi', 'L2', 'Intacte', '1'),
        ('Lith', 'A3', 'Intacte', '4'),
        ('Lith', 'B3', 'Intacte', '3'),
        ('Lith', 'B4', 'Intacte', '1'),
        ('Lith', 'B5', 'Intacte', '3'),
        ('Lith', 'B6', 'Intacte', '4'),
        ('Lith', 'C2', 'Intacte', '6'),
        ('Lith', 'C4', 'Intacte', '4'),
        ('Lith', 'H2', 'Intacte', '6'),
        ('Lith', 'K2', 'Intacte', '14'),
        ('Lith', 'M4', 'Intacte', '8'),
        ('Lith', 'O1', 'Intacte', '4'),
        ('Lith', 'O2', 'Intacte', '6'),
        ('Lith', 'P1', 'Intacte', '3'),
        ('Lith', 'P2', 'Intacte', '16'),
        ('Lith', 'T2', 'Intacte', '5'),
        ('Lith', 'V5', 'Intacte', '3'),
        ('Lith', 'Z2', 'Intacte', '1'),
        ('Meso', 'B2', 'Intacte', '1')
    ],
    '5.png': [
        ('Meso', 'D3', 'Intacte', '6'),
        ('Meso', 'E2', 'Intacte', '5'),
        ('Meso', 'M3', 'Impeccable', '1'),
        ('Meso', 'M3', 'Intacte', '2'),
        ('Meso', 'O3', 'Intacte', '3'),
        ('Meso', 'R1', 'Intacte', '5'),
        ('Meso', 'T1', 'Intacte', '4'),
        ('Meso', 'T3', 'Intacte', '9'),
        ('Meso', 'Z3', 'Intacte', '3'),
        ('Neo', 'G1', 'Intacte', '1'),
        ('Neo', 'N8', 'Intacte', '1'),
        ('Neo', 'V8', 'Intacte', '3'),
        ('Neo', 'Z2', 'Intacte', '2')
    ],
    '6.png': [
        ('Lith', 'S7', 'Intacte', '23'),
        ('Lith', 'T1', 'Intacte', '24'),
        ('Lith', 'V5', 'Intacte', '5'),
        ('Lith', 'Z1', 'Intacte', '7'),
        ('Lith', 'Z2', 'Intacte', '11'),
        ('Meso', 'A1', 'Intacte', '1'),
        ('Meso', 'B2', 'Intacte', '8'),
        ('Meso', 'D2', 'Intacte', '1'),
        ('Meso', 'D3', 'Intacte', '7'),
        ('Meso', 'E2', 'Intacte', '1'),
        ('Meso', 'F1', 'Intacte', '1'),
        ('Meso', 'F3', 'Intacte', '1'),
        ('Meso', 'G1', 'Intacte', '2'),
        ('Meso', 'H1', 'Intacte', '3'),
        ('Meso', 'M3', 'Intacte', '3'),
        ('Meso', 'N5', 'Intacte', '10'),
        ('Meso', 'O2', 'Intacte', '5'),
        ('Meso', 'R1', 'Intacte', '2'),
        ('Meso', 'S2', 'Intacte', '1'),
        ('Meso', 'S4', 'Intacte', '1')
    ],
    '7.png': [
        ('Lith', 'B3', 'Intacte', '7'),
        ('Lith', 'B4', 'Intacte', '1'),
        ('Lith', 'B5', 'Intacte', '7'),
        ('Lith', 'B6', 'Intacte', '6'),
        ('Lith', 'C2', 'Intacte', '17'),
        ('Lith', 'C3', 'Intacte', '2'),
        ('Lith', 'C4', 'Intacte', '5'),
        ('Lith', 'G2', 'Intacte', '3'),
        ('Lith', 'H1', 'Intacte', '1'),
        ('Lith', 'H2', 'Intacte', '25'),
        ('Lith', 'K2', 'Intacte', '8'),
        ('Lith', 'M2', 'Intacte', '1'),
        ('Lith', 'M3', 'Intacte', '1'),
        ('Lith', 'M4', 'Intacte', '9'),
        ('Lith', 'N3', 'Intacte', '6'),
        ('Lith', 'O1', 'Intacte', '13'),
        ('Lith', 'P1', 'Intacte', '27'),
        ('Lith', 'P2', 'Eclatante', '1'),
        ('Lith', 'P2', 'Intacte', '9'),
        ('Lith', 'S4', 'Intacte', '3')
    ],
    '8.png': [
        ('Lith', 'V2', 'Eclatante', '2'),
        ('Meso', 'E2', 'Eclatante', '1'),
        ('Meso', 'Z3', 'Eclatante', '1'),
        ('Neo', 'B4', 'Eclatante', '1'),
        ('Neo', 'M1', 'Eclatante', '1'),
        ('Neo', 'N3', 'Eclatante', '4'),
        ('Neo', 'R1', 'Eclatante', '1'),
        ('Neo', 'V4', 'Eclatante', '11'),
        ('Neo', 'M1', 'Exceptionnelle', '1'),
        ('Axi', 'A1', 'Intacte', '8'),
        ('Axi', 'A3', 'Intacte', '1'),
        ('Axi', 'A4', 'Intacte', '3'),
        ('Axi', 'G1', 'Intacte', '1'),
        ('Axi', 'H4', 'Intacte', '6'),
        ('Axi', 'K3', 'Intacte', '3'),
        ('Axi', 'L2', 'Intacte', '3'),
        ('Axi', 'L3', 'Intacte', '1'),
        ('Axi', 'N2', 'Intacte', '5'),
        ('Axi', 'T1', 'Intacte', '4'),
        ('Axi', 'T2', 'Intacte', '6')
    ],
    '9.png': [
        ('Lith', 'B6', 'Eclatante', '1'),
        ('Lith', 'C4', 'Eclatante', '1'),
        ('Lith', 'M4', 'Eclatante', '1'),
        ('Lith', 'O2', 'Eclatante', '1'),
        ('Neo', 'O1', 'Eclatante', '1'),
        ('Axi', 'A5', 'Intacte', '3'),
        ('Axi', 'K5', 'Intacte', '1'),
        ('Axi', 'S4', 'Intacte', '2'),
        ('Axi', 'V5', 'Intacte', '1'),
        ('Lith', 'A2', 'Intacte', '10'),
        ('Lith', 'A3', 'Intacte', '5'),
        ('Lith', 'B2', 'Intacte', '4'),
        ('Lith', 'B5', 'Intacte', '4'),
        ('Lith', 'B6', 'Intacte', '11'),
        ('Lith', 'C2', 'Intacte', '1'),
        ('Lith', 'C3', 'Intacte', '2'),
        ('Lith', 'C4', 'Intacte', '16'),
        ('Lith', 'H2', 'Intacte', '13'),
        ('Lith', 'K1', 'Intacte', '4'),
        ('Lith', 'K2', 'Intacte', '11')
    ],
    '10.png': [
        ('Axi', 'A1', 'Intacte', '1'),
        ('Axi', 'A4', 'Intacte', '1'),
        ('Axi', 'A6', 'Eclatante', '1'),
        ('Axi', 'H3', 'Intacte', '1'),
        ('Axi', 'H4', 'Intacte', '1'),
        ('Axi', 'K3', 'Intacte', '1'),
        ('Axi', 'K4', 'Intacte', '1'),
        ('Axi', 'K5', 'Intacte', '1'),
        ('Axi', 'M1', 'Intacte', '1'),
        ('Axi', 'N2', 'Intacte', '1'),
        ('Axi', 'O3', 'Intacte', '1'),
        ('Axi', 'O4', 'Intacte', '1'),
        ('Axi', 'P2', 'Intacte', '1'),
        ('Axi', 'R2', 'Intacte', '1'),
        ('Axi', 'S3', 'Intacte', '1'),
        ('Axi', 'T3', 'Intacte', '1'),
        ('Lith', 'A2', 'Intacte', '9'),
        ('Lith', 'A3', 'Intacte', '27'),
        ('Lith', 'B2', 'Intacte', '4'),
        ('Lith', 'B3', 'Intacte', '7')
    ],
    '11.png': [
        ('Lith', 'B4', 'Intacte', '3'),
        ('Lith', 'B5', 'Intacte', '7'),
        ('Lith', 'B6', 'Intacte', '10'),
        ('Lith', 'C2', 'Intacte', '8'),
        ('Lith', 'C3', 'Intacte', '1'),
        ('Lith', 'C4', 'Intacte', '22'),
        ('Lith', 'H1', 'Intacte', '1'),
        ('Lith', 'H2', 'Intacte', '25'),
        ('Lith', 'K2', 'Intacte', '23'),
        ('Lith', 'L1', 'Intacte', '8'),
        ('Lith', 'M2', 'Intacte', '1'),
        ('Lith', 'M3', 'Intacte', '1'),
        ('Lith', 'M4', 'Intacte', '24'),
        ('Lith', 'N3', 'Intacte', '5'),
        ('Lith', 'O1', 'Intacte', '13'),
        ('Lith', 'O2', 'Intacte', '1'),
        ('Lith', 'P1', 'Intacte', '27'),
        ('Lith', 'P2', 'Intacte', '17'),
        ('Lith', 'P2', 'Eclatante', '1'),
        ('Lith', 'S4', 'Intacte', '3')
    ],
    '12.png': [
        ('Lith', 'S7', 'Intacte', '18'),
        ('Lith', 'S8', 'Intacte', '1'),
        ('Lith', 'T1', 'Intacte', '25'),
        ('Lith', 'V5', 'Intacte', '5'),
        ('Lith', 'W1', 'Intacte', '2'),
        ('Lith', 'Z1', 'Intacte', '7'),
        ('Lith', 'Z2', 'Intacte', '11'),
        ('Meso', 'A1', 'Intacte', '1'),
        ('Meso', 'A2', 'Intacte', '3'),
        ('Meso', 'B2', 'Intacte', '2'),
        ('Meso', 'D3', 'Intacte', '6'),
        ('Meso', 'D4', 'Intacte', '1'),
        ('Meso', 'E2', 'Intacte', '7'),
        ('Meso', 'E3', 'Intacte', '1'),
        ('Meso', 'F1', 'Intacte', '1'),
        ('Meso', 'G1', 'Intacte', '1'),
        ('Meso', 'H1', 'Intacte', '2'),
        ('Meso', 'K2', 'Intacte', '1'),
        ('Meso', 'M3', 'Intacte', '1'),
        ('Meso', 'N5', 'Intacte', '7')
    ],
    '13.png': [
        ('Meso', 'N6', 'Intacte', '1'),
        ('Meso', 'N7', 'Intacte', '2'),
        ('Meso', 'O2', 'Intacte', '3'),
        ('Meso', 'O3', 'Intacte', '2'),
        ('Meso', 'R1', 'Intacte', '2'),
        ('Meso', 'S2', 'Intacte', '1'),
        ('Meso', 'S4', 'Intacte', '1'),
        ('Meso', 'S5', 'Intacte', '1'),
        ('Meso', 'S7', 'Intacte', '3'),
        ('Meso', 'S8', 'Intacte', '1'),
        ('Meso', 'T1', 'Intacte', '35'),
        ('Meso', 'T2', 'Intacte', '3'),
        ('Meso', 'T3', 'Intacte', '21'),
        ('Meso', 'V3', 'Intacte', '1'),
        ('Meso', 'W1', 'Intacte', '4'),
        ('Meso', 'Z1', 'Intacte', '10'),
        ('Meso', 'Z2', 'Intacte', '1'),
        ('Meso', 'Z3', 'Intacte', '21'),
        ('Neo', 'A1', 'Intacte', '1'),
        ('Neo', 'A2', 'Intacte', '5')
    ],
    '14.png': [
        ('Meso', 'N6', 'Intacte', '1'),
        ('Meso', 'N7', 'Intacte', '2'),
        ('Meso', 'O2', 'Intacte', '3'),
        ('Meso', 'O3', 'Intacte', '2'),
        ('Meso', 'R1', 'Intacte', '2'),
        ('Meso', 'S2', 'Intacte', '1'),
        ('Meso', 'S4', 'Intacte', '1'),
        ('Meso', 'S5', 'Intacte', '1'),
        ('Meso', 'S7', 'Intacte', '3'),
        ('Meso', 'S8', 'Intacte', '1'),
        ('Meso', 'T1', 'Intacte', '35'),
        ('Meso', 'T2', 'Intacte', '3'),
        ('Meso', 'T3', 'Intacte', '21'),
        ('Meso', 'V3', 'Intacte', '1'),
        ('Meso', 'W1', 'Intacte', '4'),
        ('Meso', 'Z1', 'Intacte', '10'),
        ('Meso', 'Z2', 'Intacte', '1'),
        ('Meso', 'Z3', 'Intacte', '21'),
        ('Neo', 'A1', 'Intacte', '1'),
        ('Neo', 'A2', 'Intacte', '5')
    ],
    '15.png': [
        ('Neo', 'B2', 'Intacte', '1'),
        ('Neo', 'C1', 'Intacte', '5'),
        ('Neo', 'G1', 'Intacte', '1'),
        ('Neo', 'H1', 'Intacte', '1'),
        ('Neo', 'K1', 'Intacte', '1'),
        ('Neo', 'M1', 'Intacte', '1'),
        ('Neo', 'M2', 'Intacte', '4'),
        ('Neo', 'N5', 'Intacte', '1'),
        ('Neo', 'N8', 'Intacte', '1'),
        ('Neo', 'N10', 'Intacte', '1'),
        ('Neo', 'R1', 'Intacte', '1'),
        ('Neo', 'R2', 'Intacte', '4'),
        ('Neo', 'S3', 'Intacte', '1'),
        ('Neo', 'S7', 'Intacte', '1'),
        ('Neo', 'S11', 'Intacte', '1'),
        ('Neo', 'S12', 'Intacte', '2'),
        ('Neo', 'T1', 'Intacte', '1'),
        ('Neo', 'V2', 'Intacte', '1'),
        ('Neo', 'V5', 'Intacte', '1'),
        ('Neo', 'V6', 'Intacte', '1')
    ],
    '16.png': [
        ('Neo', 'R1', 'Intacte', '1'),
        ('Neo', 'R2', 'Intacte', '4'),
        ('Neo', 'S3', 'Intacte', '1'),
        ('Neo', 'S7', 'Intacte', '1'),
        ('Neo', 'S11', 'Intacte', '1'),
        ('Neo', 'S12', 'Intacte', '2'),
        ('Neo', 'T1', 'Intacte', '1'),
        ('Neo', 'V2', 'Intacte', '1'),
        ('Neo', 'V5', 'Intacte', '1'),
        ('Neo', 'V6', 'Intacte', '1'),
        ('Neo', 'Z1', 'Intacte', '2'),
        ('Neo', 'Z2', 'Intacte', '9'),
        ('Neo', 'Z3', 'Intacte', '2'),
        ('Neo', 'Z4', 'Intacte', '4')
    ],
    '17.png': [
        ('Axi', 'A3', 'Intacte', '1'),
        ('Axi', 'A4', 'Intacte', '1'),
        ('Axi', 'A6', 'Intacte', '1'),
        ('Axi', 'D1', 'Intacte', '1'),
        ('Axi', 'E2', 'Intacte', '1'),
        ('Axi', 'G2', 'Intacte', '6'),
        ('Axi', 'G3', 'Intacte', '2'),
        ('Axi', 'H3', 'Intacte', '1'),
        ('Axi', 'H4', 'Intacte', '1'),
        ('Axi', 'K2', 'Intacte', '1'),
        ('Axi', 'K5', 'Intacte', '1'),
        ('Axi', 'M1', 'Intacte', '1'),
        ('Axi', 'N2', 'Intacte', '1'),
        ('Axi', 'O1', 'Intacte', '1'),
        ('Axi', 'O2', 'Intacte', '1'),
        ('Axi', 'P2', 'Intacte', '3'),
        ('Axi', 'S3', 'Intacte', '6'),
        ('Axi', 'S5', 'Intacte', '1'),
        ('Axi', 'T2', 'Intacte', '2'),
        ('Axi', 'T3', 'Intacte', '1')
    ],
    '18.png': [
        ('Axi', 'V6', 'Intacte', '1'),
        ('Lith', 'A2', 'Intacte', '2'),
        ('Lith', 'A3', 'Intacte', '13'),
        ('Lith', 'B2', 'Intacte', '5'),
        ('Lith', 'B3', 'Intacte', '2'),
        ('Lith', 'B4', 'Intacte', '1'),
        ('Lith', 'B5', 'Intacte', '4'),
        ('Lith', 'B6', 'Intacte', '7'),
        ('Lith', 'C2', 'Intacte', '4'),
        ('Lith', 'C3', 'Intacte', '2'),
        ('Lith', 'C4', 'Intacte', '9'),
        ('Lith', 'C5', 'Intacte', '1'),
        ('Lith', 'D1', 'Intacte', '4'),
        ('Lith', 'H1', 'Intacte', '1'),
        ('Lith', 'H2', 'Intacte', '6'),
        ('Lith', 'K1', 'Intacte', '6'),
        ('Lith', 'K2', 'Intacte', '10'),
        ('Lith', 'K3', 'Intacte', '1'),
        ('Lith', 'L1', 'Intacte', '6'),
        ('Lith', 'L2', 'Intacte', '2')
    ],
    '19.png': [
        ('Lith', 'M3', 'Intacte', '3'),
        ('Lith', 'M4', 'Intacte', '8'),
        ('Lith', 'N1', 'Intacte', '1'),
        ('Lith', 'N2', 'Intacte', '6'),
        ('Lith', 'N3', 'Intacte', '5'),
        ('Lith', 'O1', 'Intacte', '6'),
        ('Lith', 'O2', 'Intacte', '2'),
        ('Lith', 'P1', 'Intacte', '8'),
        ('Lith', 'P2', 'Intacte', '7'),
        ('Lith', 'S4', 'Intacte', '5'),
        ('Lith', 'S5', 'Intacte', '5'),
        ('Lith', 'S7', 'Intacte', '3'),
        ('Lith', 'S8', 'Intacte', '2'),
        ('Lith', 'T1', 'Intacte', '3'),
        ('Lith', 'T2', 'Intacte', '2'),
        ('Lith', 'V2', 'Intacte', '8'),
        ('Lith', 'V3', 'Intacte', '8'),
        ('Lith', 'V4', 'Intacte', '1'),
        ('Lith', 'V5', 'Intacte', '2'),
        ('Lith', 'W1', 'Intacte', '5')
    ],
    '20.png': [
        ('Meso', 'A2', 'Intacte', '7'),
        ('Meso', 'B2', 'Intacte', '5'),
        ('Meso', 'B3', 'Intacte', '1'),
        ('Meso', 'D1', 'Intacte', '13'),
        ('Meso', 'D2', 'Intacte', '1'),
        ('Meso', 'D3', 'Intacte', '3'),
        ('Meso', 'D4', 'Intacte', '2'),
        ('Meso', 'E2', 'Intacte', '17'),
        ('Meso', 'E3', 'Intacte', '3'),
        ('Meso', 'F1', 'Intacte', '11'),
        ('Meso', 'G1', 'Intacte', '7'),
        ('Meso', 'H1', 'Intacte', '1'),
        ('Meso', 'K2', 'Intacte', '9'),
        ('Meso', 'M2', 'Intacte', '1'),
        ('Meso', 'M3', 'Intacte', '6'),
        ('Meso', 'N5', 'Intacte', '10'),
        ('Meso', 'N6', 'Intacte', '4'),
        ('Meso', 'N7', 'Intacte', '14'),
        ('Meso', 'O1', 'Intacte', '3'),
        ('Meso', 'O2', 'Intacte', '7')
    ],
    '21.png': [
        ('Meso', 'P1', 'Intacte', '2'),
        ('Meso', 'R1', 'Intacte', '9'),
        ('Meso', 'S2', 'Intacte', '21'),
        ('Meso', 'S3', 'Intacte', '10'),
        ('Meso', 'S4', 'Intacte', '1'),
        ('Meso', 'S6', 'Intacte', '2'),
        ('Meso', 'S7', 'Intacte', '3'),
        ('Meso', 'S8', 'Intacte', '5'),
        ('Meso', 'T1', 'Intacte', '30'),
        ('Meso', 'T2', 'Intacte', '10'),
        ('Meso', 'T3', 'Intacte', '21'),
        ('Meso', 'V1', 'Intacte', '13'),
        ('Meso', 'V2', 'Intacte', '2'),
        ('Meso', 'V3', 'Intacte', '4'),
        ('Meso', 'W1', 'Intacte', '7'),
        ('Meso', 'Z1', 'Intacte', '9'),
        ('Meso', 'Z2', 'Intacte', '1'),
        ('Meso', 'Z3', 'Intacte', '17'),
        ('Neo', 'A1', 'Intacte', '5'),
        ('Neo', 'A2', 'Intacte', '9')
    ],
    '22.png': [
        ('Neo', 'A3', 'Intacte', '1'),
               ('Neo', 'B1', 'Intacte', '2'),
               ('Neo', 'B2', 'Intacte', '5'),
               ('Neo', 'B4', 'Intacte', '4'),
               ('Neo', 'B5', 'Intacte', '5'),
               ('Neo', 'C1', 'Intacte', '4'),
               ('Neo', 'G1', 'Intacte', '9'),
               ('Neo', 'H1', 'Intacte', '2'),
               ('Neo', 'H2', 'Intacte', '2'),
               ('Neo', 'K1', 'Intacte', '12'),
               ('Neo', 'M1', 'Intacte', '9'),
               ('Neo', 'M2', 'Intacte', '10'),
               ('Neo', 'N3', 'Intacte', '7'),
               ('Neo', 'N4', 'Intacte', '8'),
               ('Neo', 'N5', 'Intacte', '8'),
               ('Neo', 'N8', 'Intacte', '2'),
               ('Neo', 'N10', 'Intacte', '9'),
               ('Neo', 'R1', 'Intacte', '1'),
               ('Neo', 'R2', 'Intacte', '11'),
               ('Neo', 'S5', 'Intacte', '2')
               ],
    '23.png': [
        ('Neo', 'S7', 'Intacte', '9'),
               ('Neo', 'S9', 'Intacte', '4'),
               ('Neo', 'S11', 'Intacte', '3'),
               ('Neo', 'S13', 'Intacte', '1'),
               ('Neo', 'T1', 'Intacte', '2'),
               ('Neo', 'T2', 'Intacte', '4'),
               ('Neo', 'V2', 'Intacte', '19'),
               ('Neo', 'V3', 'Intacte', '16'),
               ('Neo', 'V4', 'Intacte', '6'),
               ('Neo', 'V5', 'Intacte', '7'),
               ('Neo', 'V6', 'Intacte', '2'),
               ('Neo', 'V7', 'Intacte', '5'),
               ('Neo', 'V8', 'Intacte', '1'),
               ('Neo', 'Z1', 'Intacte', '4'),
               ('Neo', 'Z2', 'Intacte', '11'),
               ('Neo', 'Z3', 'Intacte', '7'),
               ('Neo', 'Z4', 'Intacte', '5')
    ],
    '24.png': [
        ('Lith', 'N1', 'Intacte', '3'),
               ('Lith', 'N3', 'Intacte', '9'),
               ('Lith', 'O1', 'Intacte', '3'),
               ('Lith', 'O2', 'Intacte', '2'),
               ('Lith', 'O2', 'Exceptionnelle', '1'),
               ('Lith', 'P1', 'Intacte', '16'),
               ('Lith', 'P2', 'Intacte', '11'),
               ('Lith', 'S2', 'Intacte', '1'),
               ('Lith', 'S4', 'Intacte', '10'),
               ('Lith', 'S5', 'Intacte', '1'),
               ('Lith', 'S8', 'Eclatante', '1'),
               ('Lith', 'S8', 'Intacte', '1'),
               ('Lith', 'T1', 'Intacte', '9'),
               ('Lith', 'T2', 'Intacte', '3'),
               ('Lith', 'V2', 'Intacte', '12'),
               ('Lith', 'V3', 'Intacte', '13'),
               ('Lith', 'V4', 'Intacte', '12'),
               ('Lith', 'V5', 'Intacte', '7'),
               ('Lith', 'V6', 'Intacte', '1'),
               ('Lith', 'Z1', 'Intacte', '5')
    ],
    '25.png': [
        ('Lith', 'P1', 'Intacte', '16'),
               ('Lith', 'P2', 'Intacte', '11'),
               ('Lith', 'S2', 'Intacte', '1'),
               ('Lith', 'S4', 'Intacte', '10'),
               ('Lith', 'S5', 'Intacte', '1'),
               ('Lith', 'S8', 'Eclatante', '1'),
               ('Lith', 'S8', 'Intacte', '1'),
               ('Lith', 'T1', 'Intacte', '9'),
               ('Lith', 'T2', 'Intacte', '3'),
               ('Lith', 'V2', 'Intacte', '12'),
               ('Lith', 'V3', 'Intacte', '13'),
               ('Lith', 'V4', 'Intacte', '12'),
               ('Lith', 'V5', 'Intacte', '7'),
               ('Lith', 'V6', 'Intacte', '1'),
               ('Lith', 'Z1', 'Intacte', '5'),
               ('Lith', 'Z2', 'Eclatante', '1'),
               ('Lith', 'Z2', 'Intacte', '1')
    ],
    '26.png': [
        ('Meso', 'A1', 'Intacte', '1'),
               ('Meso', 'A2', 'Intacte', '8'),
               ('Meso', 'B2', 'Intacte', '3'),
               ('Meso', 'B3', 'Intacte', '3'),
               ('Meso', 'C3', 'Intacte', '1'),
               ('Meso', 'D1', 'Intacte', '2'),
               ('Meso', 'D2', 'Intacte', '4'),
               ('Meso', 'D3', 'Intacte', '6'),
               ('Meso', 'D4', 'Intacte', '2'),
               ('Meso', 'E2', 'Eclatante', '1'),
               ('Meso', 'E2', 'Intacte', '14'),
               ('Meso', 'E3', 'Intacte', '6'),
               ('Meso', 'F1', 'Intacte', '9'),
               ('Meso', 'F2', 'Intacte', '2'),
               ('Meso', 'G1', 'Intacte', '6'),
               ('Meso', 'H1', 'Intacte', '4'),
               ('Meso', 'K1', 'Intacte', '1'),
               ('Meso', 'K2', 'Intacte', '9'),
               ('Meso', 'M2', 'Intacte', '1'),
               ('Meso', 'M3', 'Intacte', '6')
    ],
    '27.png': [
        ('Meso', 'S3', 'Intacte', '11'),
        ('Meso', 'S4', 'Intacte', '5'),
        ('Meso', 'S5', 'Intacte', '2'),
        ('Meso', 'S6', 'Intacte', '6'),
        ('Meso', 'S7', 'Intacte', '3'),
        ('Meso', 'S8', 'Intacte', '5'),
        ('Meso', 'S9', 'Intacte', '9'),
        ('Meso', 'T1', 'Intacte', '41'),
        ('Meso', 'T2', 'Intacte', '11'),
        ('Meso', 'T3', 'Intacte', '20'),
        ('Meso', 'V1', 'Intacte', '2'),
        ('Meso', 'V2', 'Intacte', '1'),
        ('Meso', 'V3', 'Intacte', '9'),
        ('Meso', 'V4', 'Intacte', '2'),
        ('Meso', 'V5', 'Intacte', '2'),
        ('Meso', 'W1', 'Intacte', '2'),
        ('Meso', 'Z1', 'Intacte', '13'),
        ('Meso', 'Z2', 'Intacte', '2'),
        ('Meso', 'Z3', 'Intacte', '16')
    ],
    '28.png': [
        ('Meso', 'N1', 'Intacte', '1'),
               ('Meso', 'N4', 'Intacte', '2'),
               ('Meso', 'N6', 'Intacte', '3'),
               ('Meso', 'N7', 'Intacte', '3'),
               ('Meso', 'N8', 'Intacte', '2'),
               ('Meso', 'O1', 'Intacte', '1'),
               ('Meso', 'O2', 'Intacte', '14'),
               ('Meso', 'R1', 'Intacte', '10'),
               ('Meso', 'S1', 'Intacte', '1'),
               ('Meso', 'S2', 'Intacte', '19'),
               ('Meso', 'S3', 'Intacte', '11'),
               ('Meso', 'S4', 'Intacte', '5'),
               ('Meso', 'S5', 'Intacte', '2'),
               ('Meso', 'S6', 'Intacte', '6'),
               ('Meso', 'S7', 'Intacte', '3'),
               ('Meso', 'S8', 'Intacte', '5'),
               ('Meso', 'S9', 'Intacte', '9'),
               ('Meso', 'T1', 'Intacte', '41'),
               ('Meso', 'T2', 'Intacte', '11'),
               ('Meso', 'T3', 'Intacte', '20')
               ],
    '29.png': [
        ('Neo', 'A1', 'Intacte', '6'),
               ('Neo', 'A2', 'Eclatante', '1'),
               ('Neo', 'A2', 'Intacte', '14'),
               ('Neo', 'A3', 'Intacte', '4'),
               ('Neo', 'A4', 'Intacte', '20'),
               ('Neo', 'B1', 'Intacte', '2'),
               ('Neo', 'B2', 'Intacte', '5'),
               ('Neo', 'B5', 'Intacte', '4'),
               ('Neo', 'C1', 'Intacte', '14'),
               ('Neo', 'E1', 'Intacte', '1'),
               ('Neo', 'G1', 'Intacte', '7'),
               ('Neo', 'H1', 'Intacte', '5'),
               ('Neo', 'H2', 'Intacte', '4'),
               ('Neo', 'K1', 'Intacte', '8'),
               ('Neo', 'K2', 'Intacte', '3'),
               ('Neo', 'L1', 'Intacte', '1'),
               ('Neo', 'M1', 'Intacte', '3'),
               ('Neo', 'M2', 'Intacte', '15'),
               ('Neo', 'N3', 'Intacte', '9'),
               ('Neo', 'N4', 'Intacte', '8')
    ],
    '30.png': [
        ('Neo', 'N5', 'Intacte', '4'),
               ('Neo', 'N7', 'Intacte', '1'),
               ('Neo', 'N8', 'Intacte', '4'),
               ('Neo', 'N9', 'Intacte', '4'),
               ('Neo', 'N10', 'Intacte', '8'),
               ('Neo', 'R1', 'Intacte', '2'),
               ('Neo', 'R1', 'Eclatante', '1'),
               ('Neo', 'R2', 'Intacte', '10'),
               ('Neo', 'S1', 'Intacte', '1'),
               ('Neo', 'S3', 'Intacte', '3'),
               ('Neo', 'S5', 'Intacte', '3'),
               ('Neo', 'S7', 'Intacte', '13'),
               ('Neo', 'S8', 'Intacte', '4'),
               ('Neo', 'S9', 'Intacte', '5'),
               ('Neo', 'S11', 'Intacte', '6'),
               ('Neo', 'S13', 'Intacte', '6'),
               ('Neo', 'T1', 'Eclatante', '3'),
               ('Neo', 'T2', 'Intacte', '2'),
               ('Neo', 'V2', 'Intacte', '21'),
               ('Neo', 'V3', 'Intacte', '16')
    ],
    '31.png': [
        ('Axi', 'L5', 'Intacte', '5'),
               ('Axi', 'N1', 'Eclatante', '1'),
               ('Axi', 'N2', 'Eclatante', '2'),
               ('Axi', 'N4', 'Eclatante', '1'),
               ('Axi', 'O1', 'Intacte', '2'),
               ('Axi', 'O4', 'Intacte', '1'),
               ('Axi', 'P1', 'Intacte', '1'),
               ('Axi', 'P2', 'Intacte', '7'),
               ('Axi', 'S3', 'Eclatante', '1'),
               ('Axi', 'S3', 'Intacte', '4'),
               ('Axi', 'S4', 'Intacte', '1'),
               ('Axi', 'S4', 'Eclatante', '2'),
               ('Axi', 'T2', 'Intacte', '7'),
               ('Axi', 'T3', 'Intacte', '2'),
               ('Axi', 'V6', 'Intacte', '2'),
               ('Axi', 'V7', 'Intacte', '2')
    ],
    '32.png': [
        ('Axi', 'A4', 'Intacte', '3'),
               ('Axi', 'A4', 'Eclatante', '1'),
               ('Axi', 'A5', 'Eclatante', '2'),
               ('Axi', 'A7', 'Intacte', '6'),
               ('Axi', 'D1', 'Intacte', '4'),
               ('Axi', 'E1', 'Eclatante', '1'),
               ('Axi', 'G2', 'Intacte', '4'),
               ('Axi', 'G3', 'Intacte', '2'),
               ('Axi', 'H4', 'Eclatante', '1'),
               ('Axi', 'H4', 'Intacte', '4'),
               ('Axi', 'K5', 'Eclatante', '1'),
               ('Axi', 'K5', 'Intacte', '2'),
               ('Axi', 'L2', 'Intacte', '2'),
               ('Axi', 'L3', 'Intacte', '2'),
               ('Axi', 'L5', 'Eclatante', '2'),
               ('Axi', 'L5', 'Intacte', '5'),
               ('Axi', 'N1', 'Eclatante', '1'),
               ('Axi', 'N2', 'Eclatante', '2'),
               ('Axi', 'N4', 'Eclatante', '1'),
               ('Axi', 'O1', 'Intacte', '2')
    ],
    '33.png': [
        ('Lith', 'M4', 'Eclatante', '4'),
               ('Meso', 'D4', 'Eclatante', '1'),
               ('Axi', 'B3', 'Intacte', '1'),
               ('Axi', 'T3', 'Intacte', '2'),
               ('Lith', 'A2', 'Intacte', '9'),
               ('Lith', 'A3', 'Intacte', '10'),
               ('Lith', 'B2', 'Intacte', '2'),
               ('Lith', 'B4', 'Intacte', '1'),
               ('Lith', 'B5', 'Intacte', '4'),
               ('Lith', 'B6', 'Intacte', '11'),
               ('Lith', 'C3', 'Intacte', '2'),
               ('Lith', 'C4', 'Intacte', '45'),
               ('Lith', 'C5', 'Intacte', '8'),
               ('Lith', 'D1', 'Intacte', '19'),
               ('Lith', 'H2', 'Intacte', '12'),
               ('Lith', 'K1', 'Intacte', '2'),
               ('Lith', 'K2', 'Intacte', '20'),
               ('Lith', 'K3', 'Intacte', '4'),
               ('Lith', 'L1', 'Intacte', '3'),
               ('Lith', 'L2', 'Intacte', '23')
               ],
    '35.png': [
        ('Axi', 'A3', 'Intacte', '1'),
               ('Axi', 'A4', 'Intacte', '1'),
               ('Axi', 'A6', 'Intacte', '1'),
               ('Axi', 'A7', 'Intacte', '6'),
               ('Axi', 'A9', 'Intacte', '2'),
               ('Axi', 'D1', 'Intacte', '1'),
               ('Axi', 'G2', 'Intacte', '1'),
               ('Axi', 'G3', 'Intacte', '2'),
               ('Axi', 'H4', 'Intacte', '1'),
               ('Axi', 'K2', 'Intacte', '1'),
               ('Axi', 'K5', 'Intacte', '1'),
               ('Axi', 'N2', 'Intacte', '1'),
               ('Axi', 'P2', 'Intacte', '2'),
               ('Axi', 'S3', 'Intacte', '2'),
               ('Axi', 'S5', 'Intacte', '1'),
               ('Axi', 'T2', 'Intacte', '1'),
               ('Axi', 'T3', 'Intacte', '3'),
               ('Axi', 'V9', 'Intacte', '1'),
               ('Lith', 'A2', 'Intacte', '1'),
               ('Lith', 'A3', 'Intacte', '10')
    ],
    '36.png': [
        ('Lith', 'B2', 'Intacte', '4'),
               ('Lith', 'B3', 'Intacte', '1'),
               ('Lith', 'B4', 'Intacte', '1'),
               ('Lith', 'B5', 'Intacte', '2'),
               ('Lith', 'B6', 'Intacte', '6'),
               ('Lith', 'C2', 'Intacte', '4'),
               ('Lith', 'C3', 'Intacte', '2'),
               ('Lith', 'C4', 'Intacte', '19'),
               ('Lith', 'C5', 'Intacte', '2'),
               ('Lith', 'D1', 'Intacte', '15'),
               ('Lith', 'H1', 'Intacte', '1'),
               ('Lith', 'H2', 'Intacte', '6'),
               ('Lith', 'K1', 'Intacte', '6'),
               ('Lith', 'K2', 'Intacte', '8'),
               ('Lith', 'K3', 'Intacte', '7'),
               ('Lith', 'L1', 'Intacte', '5'),
               ('Lith', 'L2', 'Intacte', '22'),
               ('Lith', 'M3', 'Intacte', '3'),
               ('Lith', 'M4', 'Intacte', '25'),
               ('Lith', 'N1', 'Intacte', '1')
    ],
    '37.png': [
        ('Lith', 'N2', 'Intacte', '6'),
               ('Lith', 'N3', 'Intacte', '5'),
               ('Lith', 'O1', 'Intacte', '6'),
               ('Lith', 'P1', 'Intacte', '8'),
               ('Lith', 'P2', 'Intacte', '7'),
               ('Lith', 'S4', 'Intacte', '5'),
               ('Lith', 'S5', 'Intacte', '5'),
               ('Lith', 'S7', 'Intacte', '3'),
               ('Lith', 'S8', 'Intacte', '14'),
               ('Lith', 'T1', 'Intacte', '3'),
               ('Lith', 'T2', 'Intacte', '2'),
               ('Lith', 'V2', 'Intacte', '8'),
               ('Lith', 'V3', 'Intacte', '7'),
               ('Lith', 'V4', 'Intacte', '1'),
               ('Lith', 'V5', 'Intacte', '1'),
               ('Lith', 'V6', 'Intacte', '3'),
               ('Lith', 'V7', 'Intacte', '6'),
               ('Lith', 'V8', 'Intacte', '5'),
               ('Lith', 'W1', 'Intacte', '4'),
               ('Lith', 'W2', 'Intacte', '3')
    ],
    '38.png': [
        ('Meso', 'A2', 'Intacte', '6'),
               ('Meso', 'B2', 'Intacte', '4'),
               ('Meso', 'B3', 'Intacte', '1'),
               ('Meso', 'B4', 'Intacte', '9'),
               ('Meso', 'C4', 'Intacte', '5'),
               ('Meso', 'D1', 'Intacte', '8'),
               ('Meso', 'D3', 'Intacte', '3'),
               ('Meso', 'D4', 'Intacte', '13'),
               ('Meso', 'E2', 'Intacte', '13'),
               ('Meso', 'E3', 'Intacte', '17'),
               ('Meso', 'F1', 'Intacte', '10'),
               ('Meso', 'G1', 'Intacte', '7'),
               ('Meso', 'K2', 'Intacte', '9'),
               ('Meso', 'L1', 'Intacte', '8'),
               ('Meso', 'M2', 'Intacte', '1'),
               ('Meso', 'M3', 'Intacte', '6'),
               ('Meso', 'N5', 'Intacte', '10'),
               ('Meso', 'N6', 'Intacte', '4'),
               ('Meso', 'N7', 'Intacte', '19'),
               ('Meso', 'N9', 'Intacte', '5')
    ],
    '39.png': [
        ('Meso', 'O1', 'Intacte', '3'),
               ('Meso', 'O2', 'Intacte', '7'),
               ('Meso', 'P1', 'Intacte', '2'),
               ('Meso', 'R1', 'Intacte', '9'),
               ('Meso', 'R2', 'Intacte', '10'),
               ('Meso', 'S2', 'Intacte', '20'),
               ('Meso', 'S3', 'Intacte', '10'),
               ('Meso', 'S6', 'Intacte', '2'),
               ('Meso', 'S7', 'Intacte', '3'),
               ('Meso', 'S8', 'Intacte', '5'),
               ('Meso', 'T1', 'Intacte', '20'),
               ('Meso', 'T2', 'Intacte', '10'),
               ('Meso', 'T3', 'Intacte', '19'),
               ('Meso', 'V1', 'Intacte', '13'),
               ('Meso', 'V2', 'Intacte', '1'),
               ('Meso', 'V3', 'Intacte', '4'),
               ('Meso', 'V6', 'Intacte', '9'),
               ('Meso', 'W1', 'Intacte', '14'),
               ('Meso', 'Z1', 'Intacte', '9'),
               ('Meso', 'Z3', 'Intacte', '17')
    ],
    '40.png': [
        ('Neo', 'A3', 'Intacte', '7'),
               ('Neo', 'A4', 'Intacte', '3'),
               ('Neo', 'B2', 'Intacte', '4'),
               ('Neo', 'B4', 'Intacte', '4'),
               ('Neo', 'C1', 'Intacte', '5'),
               ('Neo', 'G1', 'Intacte', '8'),
               ('Neo', 'G2', 'Intacte', '4'),
               ('Neo', 'H1', 'Intacte', '2'),
               ('Neo', 'H2', 'Intacte', '2'),
               ('Neo', 'I1', 'Intacte', '3'),
               ('Neo', 'K1', 'Intacte', '8'),
               ('Neo', 'M1', 'Intacte', '7'),
               ('Neo', 'M2', 'Intacte', '13'),
               ('Neo', 'N3', 'Intacte', '7'),
               ('Neo', 'N4', 'Intacte', '4'),
               ('Neo', 'N5', 'Intacte', '7'),
               ('Neo', 'N8', 'Intacte', '2'),
               ('Neo', 'N10', 'Intacte', '6'),
               ('Neo', 'R2', 'Intacte', '8'),
               ('Neo', 'R3', 'Intacte', '4')
    ],
    '41.png': [
        ('Neo', 'S5', 'Intacte', '2'),
               ('Neo', 'S7', 'Intacte', '9'),
               ('Neo', 'S9', 'Intacte', '3'),
               ('Neo', 'S11', 'Intacte', '3'),
               ('Neo', 'S13', 'Intacte', '2'),
               ('Neo', 'T1', 'Intacte', '2'),
               ('Neo', 'T2', 'Intacte', '9'),
               ('Neo', 'V2', 'Intacte', '18'),
               ('Neo', 'V3', 'Intacte', '14'),
               ('Neo', 'V4', 'Intacte', '6'),
               ('Neo', 'V5', 'Intacte', '6'),
               ('Neo', 'V6', 'Intacte', '2'),
               ('Neo', 'Z1', 'Intacte', '4'),
               ('Neo', 'Z2', 'Intacte', '9'),
               ('Neo', 'Z3', 'Intacte', '8'),
               ('Neo', 'Z4', 'Intacte', '8'),
               ('Neo', 'Z5', 'Intacte', '1'),
               ('Requiem', 'I', 'Intacte', '1'),
               ('Requiem', 'II', 'Intacte', '1'),
               ('Requiem', 'III', 'Intacte', '4')
    ],
    '50.jpg': [
        ('Lith', 'A3', 'Intacte', '20'),
               ('Lith', 'B3', 'Intacte', '5'),
               ('Lith', 'B4', 'Intacte', '8'),
               ('Lith', 'B5', 'Intacte', '22'),
               ('Lith', 'B6', 'Intacte', '9'),
               ('Lith', 'C2', 'Intacte', '5'),
               ('Lith', 'C3', 'Intacte', '19'),
               ('Lith', 'C4', 'Intacte', '52'),
               ('Lith', 'C5', 'Intacte', '1'),
               ('Lith', 'D1', 'Intacte', '11'),
               ('Lith', 'G1', 'Intacte', '7'),
               ('Lith', 'H2', 'Intacte', '21'),
               ('Lith', 'K2', 'Intacte', '46'),
               ('Lith', 'K3', 'Intacte', '4'),
               ('Lith', 'L1', 'Intacte', '27'),
               ('Lith', 'L2', 'Intacte', '16'),
               ('Lith', 'M2', 'Intacte', '7'),
               ('Lith', 'M3', 'Intacte', '5'),
               ('Lith', 'M4', 'Intacte', '32'),
               ('Lith', 'O1', 'Intacte', '15')
    ]
,
}

all_paths = os.listdir(image_base_path)


@pytest.fixture()
def tess():
    tessdata_dir = 'tessdata/'
    with PyTessBaseAPI(tessdata_dir, 'Roboto', psm=PSM.SINGLE_BLOCK, oem=OEM.LSTM_ONLY) as tess:
        yield tess


@pytest.fixture()
def pool():
    with TesserocrPool() as pool:
        yield pool


@pytest.mark.parametrize("image_name", [
    path if path in expected_results else pytest.param(path, marks=pytest.mark.skip("no expected data available"))
    for path in all_paths
])
def test_tesserocr(tess, image_name):
    image_path = os.path.join(image_base_path, image_name)
    image_input = cv2.imread(image_path)
    if image_input.shape[:2] == (900, 1600):
        image_input = cv2.resize(image_input, (1920, 1080))

    ocr = OcrCheck(tess, image_input)
    ocr_data = ocr.ocr_loop()

    assert ocr_data == expected_results[image_name]


@pytest.mark.parametrize("image_name", [
    path if path in expected_results else pytest.param(path, marks=pytest.mark.skip("no expected data available"))
    for path in all_paths
])
def test_pytesseract(image_name):
    image_path = os.path.join(image_base_path, image_name)
    image_input = cv2.imread(image_path)
    if image_input.shape[:2] == (900, 1600):
        image_input = cv2.resize(image_input, (1920, 1080))

    ocr = OcrCheck(None, image_input)
    ocr_data = ocr.ocr_loop()

    assert ocr_data == expected_results[image_name]


@pytest.mark.parametrize("image_name", [
    path if path in expected_results else pytest.param(path, marks=pytest.mark.skip("no expected data available"))
    for path in all_paths
])
def test_tesserocr_rust(pool, image_name):
    image_path = os.path.join(image_base_path, image_name)
    image_input = cv2.imread(image_path)
    if image_input.shape[:2] == (900, 1600):
        image_input = cv2.resize(image_input, (1920, 1080))

    ocr = OcrCheck(pool, image_input)
    ocr_data = ocr.ocr_loop()

    assert ocr_data == expected_results[image_name]
