# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relic.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='relic.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0brelic.proto\"\x16\n\x06MyData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x07\n\x05\x45mpty2,\n\nDataSender\x12\x1e\n\tsend_data\x12\x06.Empty\x1a\x07.MyData\"\x00\x62\x06proto3'
)




_MYDATA = _descriptor.Descriptor(
  name='MyData',
  full_name='MyData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='MyData.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=37,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['MyData'] = _MYDATA
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyData = _reflection.GeneratedProtocolMessageType('MyData', (_message.Message,), {
  'DESCRIPTOR' : _MYDATA,
  '__module__' : 'relic_pb2'
  # @@protoc_insertion_point(class_scope:MyData)
  })
_sym_db.RegisterMessage(MyData)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'relic_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_DATASENDER = _descriptor.ServiceDescriptor(
  name='DataSender',
  full_name='DataSender',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=48,
  serialized_end=92,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_data',
    full_name='DataSender.send_data',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MYDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASENDER)

DESCRIPTOR.services_by_name['DataSender'] = _DATASENDER

# @@protoc_insertion_point(module_scope)
